from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setWindowTitle('MainWindow')
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(766, 247)
        self.setIconSize(QtCore.QSize(50, 30))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 30, 741, 161))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 30, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Interval = QtWidgets.QSpinBox(self.widget)
        self.Interval.setGeometry(QtCore.QRect(150, 30, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Interval.setFont(font)
        self.Interval.setFrame(True)
        self.Interval.setProperty("value", 20)
        self.Interval.setObjectName("Interval")
        self.Unit = QtWidgets.QComboBox(self.widget)
        self.Unit.setGeometry(QtCore.QRect(240, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Unit.setFont(font)
        self.Unit.setFrame(True)
        self.Unit.setObjectName("Unit")
        self.Unit.addItem("")
        self.Unit.addItem("")
        self.Unit.addItem("")
        self.chooseFolder = QtWidgets.QPushButton(self.widget)
        self.chooseFolder.setGeometry(QtCore.QRect(390, 30, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chooseFolder.setFont(font)
        self.chooseFolder.setObjectName("chooseFolder")
        self.Sort = QtWidgets.QPushButton(self.widget)
        self.Sort.setGeometry(QtCore.QRect(580, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Sort.setFont(font)
        self.Sort.setObjectName("Sort")
        self.CreateCopy = QtWidgets.QCheckBox(self.widget)
        self.CreateCopy.setGeometry(QtCore.QRect(280, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CreateCopy.setFont(font)
        self.CreateCopy.setIconSize(QtCore.QSize(40, 40))
        self.CreateCopy.setObjectName("CreateCopy")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 25))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "PhotoSorter"))
        self.label.setText(_translate("self", "Sortuj co"))
        self.Unit.setItemText(0, _translate("self", "SEKUND"))
        self.Unit.setItemText(1, _translate("self", "MINUT"))
        self.Unit.setItemText(2, _translate("self", "DNI"))
        self.chooseFolder.setText(_translate("self", "Wybierz Folder"))
        self.Sort.setText(_translate("self", "Sortuj"))
        self.CreateCopy.setText(_translate("self", "Create Copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())
